// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import Link from 'next/link';
import './globals.css';
import NeuralBackground from '../components/NeuralBackground';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-gray-900 text-gray-100">
        <NeuralBackground />
        <nav className="bg-gray-800 p-4 shadow-md fixed w-full top-0 z-50 flex justify-between px-10">
          <a href="#home" className="text-xl font-bold">Amulya Veldandi</a>
          <div className="space-x-4">
            <a href="#about">About</a>
            <a href="#projects">Projects</a>
            <a href="#experience">Experience</a>
            <a href="#research">Research</a>
            <a href="#skills">Skills</a>
            <a href="#contact">Contact</a>
          </div>
        </nav>
        <main className="max-w-5xl mx-auto mt-20 p-6 relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}

